@server = http://localhost:3000

### register
POST {{server}}/auth/register
Content-Type: application/json

{
  "username": "jonghwan",
  "password": "1234",
  "email": "jonghwan@test.com"
}

### login
POST {{server}}/auth/login
Content-Type: application/json

{
  "password": "1234",
  "email": "jonghwan@test.com"
}

### login2
POST {{server}}/auth/login2
Content-Type: application/json

{
  "password": "1234",
  "email": "jonghwan@test.com"
}

### guard test
GET {{server}}/auth/guard-test

### login 3
POST {{server}}/auth/login3
Content-Type: application/json

{
  "password": "1234",
  "email": "jonghwan@test.com"
}

### login 3 틀린 비밀번호
POST {{server}}/auth/login3
Content-Type: application/json

{
  "password": "12345",
  "email": "jonghwan@test.com"
}

### guard test2
GET {{server}}/auth/guard-test2












### login 4
POST {{server}}/auth/login4
Content-Type: application/json

{
  "password": "1234",
  "email": "jonghwan@test.com"
}

### login 4 + guard test
GET {{server}}/auth/guard-test

### login 4 + guard test2
GET {{server}}/auth/guard-test2
